name: Pull request comment
on:
  workflow_run:
    workflows:
    - Parallel Robot Framework pipeline
    types:
    - completed

jobs:
  parallel-robot-pipeline-logs-url:
    name: Parallel Robot Framework pipeline logs URL
    if: github.event.workflow_run.pull_requests[0] != null
    runs-on: ubuntu-latest
    steps:
    - name: Comment link to combined logs into the PR
      uses: actions/github-script@v6
      with:
        script: |
          const run = context.payload.workflow_run
          const run_id = run.id
          const suite_id = run.check_suite_id
          const repo_url = context.payload.repository.html_url
          const pr_number = run.pull_requests[0].number

          const all = await github.rest.actions.listWorkflowRunArtifacts({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id,
          })

          const combined = all.data.artifacts.find(a => a.name === "combined-logs")
          const url = `${repo_url}/suites/${suite_id}/artifacts/${combined.id}`

          github.rest.issues.createComment({
            issue_number: pr_number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Combined robot framework logs for workflow [${run.name} #${run.run_number}.${run.run_attempt}](${run.html_url}) available as [artifact](${url}) (expires at \`${combined.expires_at}\`).`,
          })
